spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: Wasti786@

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  boot:
    message: "Department Service Update"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
info:
  app:
    name: "Department REST Services"
    description: "Restful Web APIs for Departments"
    version: "1.0.0"

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
